### ISSUE TITLE
Asking to authenticate after every launch.

### ISSUE THREAD

**Issue by minecraftchest1** [microsoftgraph/msgraph-training-dotnet-core#13]
After adding the authentication code, it asks to authenticate after every launch. Authentication the second time results in an error.

**Comment by jasonjoh** [comment]
It is expected that it will authenticate on every launch, the sample does no implement any token caching mechanisms. What's the error?

**Comment by minecraftchest1** [comment]
![image](https://user-images.githubusercontent.com/42992675/86145878-1ad56780-babd-11ea-9070-a13d83182869.png)

By what I understand, it is getting an authentication error, then failing with an internal error. But, I am only getting the error while running the project after downloading the project (after adding my app code).

**Comment by minecraftchest1** [comment]
I think the error might be because I reused an appid.

**Comment by jasonjoh** [comment]
Assuming your app registration matches what this app needs, it should be fine. The screenshot you're showing me looks off though: you shouldn't be seeing repeated prompts to open your browser. This should only happen once per run of the app. I see it's saying "service is unavailable to process the request". Are you by chance logging into this with a personal account (like an outlook.com user)?

**Comment by minecraftchest1** [comment]
Yes. The app I built from the "Build your first .Net Core app in 30 Minutes" works just fine. It also uses the same appid.

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jasonjoh** [comment]
Ok. I reproduced the "service is unavailable" error using my personal account, but then I ran the code a second time and it authenticated just fine. There may be intermittent issues with the Microsoft identity platform, support for this login flow for personal accounts is relatively new.

So you do not have any of these problems with the version you built from the tutorial, but the code in this repo does have the problem? Can you diff the code to see if there's anything different? (or if not, can you post your tutorial-built project somewhere I can access it, like GitHub?)

**Comment by minecraftchest1** [comment]
Here is the link to the repro with the totural built code. I'll push my latest code to it later today, as well as as branching and adding the repro code to it. I don't have acess to my dev machine right know or I would  have it done already.

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by minecraftchest1** [comment]
Forgot to post the link.

https://github.com/minecraftchest1/MicrosoftGraphTestProjects

**Comment by jasonjoh** [comment]
Doesn't look like that's complete:

```
using System;

namespace MsGraphApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

**Comment by minecraftchest1** [comment]
I thought I synced it.

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by minecraftchest1** [comment]
Its pushed now. I forgot to commit the changes last time.

**Comment by jasonjoh** [comment]
Thanks. Which project is the one you built from the tutorial that doesn't have any problems?

**Comment by minecraftchest1** [comment]
I think it is project1.
________________________________

**Comment by minecraftchest1** [comment]
It's project1

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jasonjoh** [comment]
Ok. After diffing that with the repo, there's no significant difference. Your copy doesn't have the code to get the user's events, but the auth stuff is all the same. I'm not sure that there's any action I can take on this repo based on the information I have available.

**Comment by minecraftchest1** [comment]
I'm not to concerned sense that is a test anyway. I have other projects to work on.

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
