### ISSUE TITLE
.NET Core Graph Tutorial needs permission to access resources in your organization that only an admin can grant

### ISSUE THREAD

**Issue by xyz92** [microsoftgraph/msgraph-training-dotnet-core#14]
On running the app, I see the following:

![image](https://user-images.githubusercontent.com/6519992/86188485-a2d66400-baf3-11ea-93a3-0967f6532f64.png)

I tried my account (@microsoft.com)

![image](https://user-images.githubusercontent.com/6519992/86188513-af5abc80-baf3-11ea-9ba4-b1fe2bb7e16c.png)

and it keeps saying:

![image](https://user-images.githubusercontent.com/6519992/86188600-052f6480-baf4-11ea-828c-127057682638.png)

What should I do?

**Comment by jasonjoh** [comment]
https://docs.microsoft.com/graph/quick-start-faq#after-signing-in-im-told-i-need-admin-approval

You said you're @microsoft.com. Our IT has disabled our ability to consent to any application that they have not personally approved (hence the prompt that you need admin approval). You won't be able to use your corporate account to test this. Use a demo tenant or a personal outlook.com account.

**Comment by xyz92** [comment]
Thank you!
