### ISSUE TITLE
GraphHelper does not exists error

### ISSUE THREAD

**Issue by x509cert** [microsoftgraph/msgraph-training-dotnet-core#15]
dotnet run 

yields..

Program.cs(34,13): error CS0103: The name 'GraphHelper' does not exist in the current context [C:\Users\xyzzy\source\repos\MyCal\MyCalGraph\MyCalGraph.csproj]

I copied the files from the repo, but no go. I cannot see any reference to GraphHelper anywhere... does it exist in a library? I have installed the three packages in the instructions, and I have the Graph API SDK installed...

**Comment by jasonjoh** [comment]
It's here: https://github.com/microsoftgraph/msgraph-training-dotnet-core/blob/master/demo/GraphTutorial/Graph/GraphHelper.cs. I noticed that you're using a different project name `MyCalGraph`, and presumably your namespace is also `MyCalGraph`. However, the namespace in the sample code is `GraphTutorial`, which may be your issue. Try changing the namespace in GraphHelper.cs to match the one in your Program.cs.

**Comment by x509cert** [comment]
Yeah - that was it - a silly oversight! thanks!
