### ISSUE TITLE
GraphTutorial can't sign in

### ISSUE THREAD

**Issue by MikeHillberg** [microsoftgraph/msgraph-training-dotnet-core#17]
I'm getting signin errors when I run this tutorial.

When I sign in with my MSA (same MSA used to create the app), I successfully go through the flow in the browser at microsoft.com/devicelogin, but then in the client app I get:

    Error getting signed-in user: Code: ErrorAccessDenied
    Message: Access is denied. Check credentials and try again.

When I attempt to sign in with my work account I get a "Need admin approval" message in the browser stage:

![image](https://user-images.githubusercontent.com/18429489/96050999-7a1e7400-0e2f-11eb-9ba2-60ef7b9f5e10.png)

Have the APIs changed since this tutorial was written?

**Comment by MikeHillberg** [comment]
Just realized that the second issue (admin approval) is already discussed #3

**Comment by jasonjoh** [comment]
Yep @MikeHillberg I see your an MS employee. Our IT has disabled our ability to consent to some of the permissions this tutorial uses.

Where do you get the first error, which line of code?

**Comment by MikeHillberg** [comment]
Thanks for the explanation of that part, sorry for not checking closed issues first. I was very sad to see that IT wasn't allowing Presence.Read. Graph Explorer works though, is that because that specific app is given permission?

It fails on the call to _msalClient.AcquireTokenWithDeviceCode. The browser steps work and the client returns, but throws that exception.

I am though able to get the [UWP tutorial](https://docs.microsoft.com/en-us/graph/tutorials/uwp) to work. The access token code in that case is inside the [LoginButton](https://docs.microsoft.com/en-us/windows/communitytoolkit/graph/controls/loginbutton) control, but I haven't looked at that code yet to see what the difference is.

**Comment by jasonjoh** [comment]
Yes, IT has approved Graph Explorer. Those restrictions only come into play with apps they haven't approved.

I've retried this with an MSA and it worked fine, so it *should* work. Looking closer at your error message `Error getting signed-in user: Code: ErrorAccessDenied`, it looks like it's actually failing at `return await graphClient.Me.Request().GetAsync();` Setting a breakpoint there and digging into the exception might shed some light.

**Comment by ashokgelal** [comment]
I just ran into this same issue. It throws `ErrorAccessDenied` when I passed in `MailboxSettings` permission even though I've set allowed it to access my mailbox settings.

```csharp
// ...
    return await graphClient.Me.Request().Select(u => new
    {
        u.DisplayName,
        u.MailboxSettings // only works if this is commented out
    }).GetAsync();
// ...
```

**Comment by ashokgelal** [comment]
I knew this was related to not having `MailboxSettings` in the scopes and that's what it was. I was following the tutorial and my guess is that the tutorial before missed to have `MailboxSettings` in the scope list. It looks like the tutorial is now updated to include it and I can run it successfully.

**Comment by jasonjoh** [comment]
Yes, a previous version of the tutorial did not use mailbox settings at all, so it didn't have the scope for it. @MikeHillberg is this what's happening on your end?
