### ISSUE TITLE
Missing "using" statement in tutorial code on web page

### ISSUE THREAD

**Issue by SmallRoomLabs** [microsoftgraph/msgraph-training-dotnet-core#19]
When following the steps in the tutorial at https://docs.microsoft.com/en-us/graph/tutorials/dotnet-core?tutorial-step=4 you end up with this error

```
/Users/mats/Documents/Projects/MSgraph/GraphTutorial/Graph/GraphHelper.cs(87,33): error CS0103: The name 'TZConvert' does not exist in the current context [/Users/mats/Documents/Projects/MSgraph/GraphTutorial/GraphTutorial.csproj]

The build failed. Fix the build errors and run again.
```

The fix of course is easy enough by just inserting a `using TimeZoneConverter;` into the `Graph/GraphHelper.cs` -file. Not a huge issue but it might be a bit annoying for a beginners tutorial.

**Comment by jasonjoh** [comment]
Thanks for pointing this out.
