### ISSUE TITLE
Error thrown if datetimeformat for user mailbox is missing

### ISSUE THREAD

**Issue by sinhakislay** [microsoftgraph/msgraph-training-dotnet-core#24]
**Where did you get the code?**
- [ x] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

**Describe the bug**
code throws an error if "Datetimeformat" for user is not set in Mailbox settings which was the case when I tested it

**To Reproduce**
1. Go to Step 4 https://docs.microsoft.com/en-us/graph/tutorials/dotnet-core?tutorial-step=4
2. The call to this method will fail at later stage
 ListCalendarEvents(
    user.MailboxSettings.TimeZone,
    $"{user.MailboxSettings.DateFormat} {user.MailboxSettings.TimeFormat}"
);
3. I propose that we do a check like below and set a default value or at some other place
4. static string FormatDateTimeTimeZone(
            Microsoft.Graph.DateTimeTimeZone value,
            string dateTimeFormat)
        {
            // Parse the date/time string from Graph into a DateTime
            var dateTime = DateTime.Parse(value.DateTime);
            if(dateTimeFormat != " ")
                return dateTime.ToString(dateTimeFormat);
            else
                return dateTime.ToString(DateTime.Now.ToString("MM/dd/yyyy"));
        } 

**Expected behavior**
Code should not throw an exception

**Desktop (please complete the following information):**
 - OS: Windows

**Dependency versions**
 - Authentication library (MSAL, etc.) version:
 - Graph library (Graph SDK, REST library, etc.) version:

**Comment by jasonjoh** [comment]
Thanks for reporting. Will address this in the next update.

**Comment by DanWahlin** [comment]
I hit this as well with the account I logged in with. I ended up changing it to the following just to get something going:

```csharp
var dateFormat =$"{user.MailboxSettings.DateFormat} {user.MailboxSettings.TimeFormat}".Trim();
ListCalendarEvents(user.MailboxSettings.TimeZone, dateFormat);

....

static string FormatDateTimeTimeZone(Microsoft.Graph.DateTimeTimeZone value, string dateTimeFormat)
{
    // Parse the date/time string from Graph into a DateTime
    var graphDatetime = value.DateTime;
    if (DateTime.TryParse(graphDatetime, out DateTime dateTime)) 
    {
        if (!String.IsNullOrEmpty(dateTimeFormat)) 
        {
            return dateTime.ToString(dateTimeFormat);
        }
        else {
            return $"{dateTime.ToShortDateString()} {dateTime.ToShortTimeString()}";
        }

    }
    else
    {
        return graphDatetime;
    }
}
```
