### ISSUE TITLE
Graph Authentication Setting Inconsistency

### ISSUE THREAD

**Issue by KeLorean** [microsoftgraph/msgraph-training-dotnet-core#25]
**Where did you get the code?**
Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

**Describe the bug**
There was an inconsistency with the directions in the "Register the App in the Portal" page (https://docs.microsoft.com/en-us/graph/tutorials/dotnet-core?tutorial-step=2). Step 5. says, "Select Authentication under Manage. Locate the Advanced settings section and change the Treat application as a public client toggle to Yes, then choose Save." BUT my Advanced settings looked different. I had just ignored this step at first and it gave my app an authentication error. After some troubleshooting, I realized what the directions should say is: "Select Authentication under Manage. Locate the Advanced settings section and change the Allow public client flows toggle to Yes, then choose Save." The picture should also be updated to this:
`https://imgur.com/a/U7lFaXe`

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise v.1909
 - Browser: Chrome Version 88.0.4324.190 (Official Build) 

**Dependency versions**
 - Authentication library (MSAL, etc.) version:
 - Graph library (Graph SDK, REST library, etc.) version:

**Comment by jasonjoh** [comment]
Thanks for reporting.

**Comment by z1net** [comment]
Hello! 

Thank your for this tutorial, but here is some problems:

In the red box are not correct parameters, * user scopes.
![image](https://user-images.githubusercontent.com/65300126/122639944-700eec80-d105-11eb-87b9-176a061ba701.png)

it should be like this
![image](https://user-images.githubusercontent.com/65300126/122639966-85841680-d105-11eb-9508-0323805ca82f.png)

(dotnet user-secrets set scopes "User.Read;MailboxSettings.Read;Calendars.ReadWrite")
