### ISSUE TITLE
Cannot add listed packages from tutorial in Create a .NET Core console app

### ISSUE THREAD

**Issue by pkothare** [microsoftgraph/msgraph-training-dotnet-core#27]
**Where did you get the code?**
- [ ] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [x] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

**Describe the bug**
Cannot add listed packages from tutorial in [Create a .NET Core console app](https://docs.microsoft.com/en-us/graph/tutorials/dotnet-core?source=docs&tutorial-step=1)

**To Reproduce**
1. Downloaded and installed [.NET SDK 5.0.202 x64 for Windows](https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-5.0.202-windows-x64-installer) 
2. Launched VS Code and ran the following commands in a new PowerShell terminal with no problem:
  ```
  > dotnet new console -o GraphTutorial
  
  Processing post-creation actions...
  Running 'dotnet restore' on GraphTutorial\GraphTutorial.csproj...
    Determining projects to restore...
    Restored C:\Users\pkothare\repos\GraphTutorial\GraphTutorial.csproj (in 76 ms).
  Restore succeeded.
  
  > cd .\GraphTutorial\
  > dotnet run
  Hello World!
  
  ```
3. When running the `dotnet add package` commands to add the relevant packages in the tutorial, I saw the following errors:
  ```
  > dotnet add package Microsoft.Extensions.Configuration.UserSecrets --version 5.0.0
    Determining projects to restore...
    Writing C:\Users\pkothare\AppData\Local\Temp\tmp7454.tmp
  info : Adding PackageReference for package 'Microsoft.Extensions.Configuration.UserSecrets' into project 'C:\Users\pkothare\repos\GraphTutorial\GraphTutorial.csproj'.
  info : Restoring packages for C:\Users\pkothare\repos\GraphTutorial\GraphTutorial.csproj...
  error: NU1100: Unable to resolve 'Microsoft.Extensions.Configuration.UserSecrets (>= 5.0.0)' for 'net5.0'.
  error: Package 'Microsoft.Extensions.Configuration.UserSecrets' is incompatible with 'all' frameworks in project 'C:\Users\pkothare\repos\GraphTutorial\GraphTutorial.csproj'.
  ```
  Similar errors were thrown for all other `dotnet add package` commands.

**Expected behavior**
[NU1100 ](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1100) should not be thrown as an error and the package should be added to the project.

**Desktop (please complete the following information):**
 - OS: Windows 10 Insider Preview 10.0.21370

**Dependency versions**
 - .NET SDK 5.0.202 x64 for Windows

**Comment by jasonjoh** [comment]
@pkothare sorry you're running into this error. I do not reproduce it. This seems to be a problem with your development machine. What is the output if you run this command:

```
dotnet nuget list source
```

**Comment by pkothare** [comment]
@jasonjoh, I get the following:

```
PS C:\Users\pkothare\repos\GraphTutorial> dotnet nuget list source

No sources found.
PS C:\Users\pkothare\repos\GraphTutorial> 
```
I would have assumed that installing the .NET SDK 5.0.202 would have automatically configured my NuGet sources. If that's not the case, then can you please point me to what sources should be added to move forward?

**Comment by jasonjoh** [comment]
Well I don't know for sure, I would have thought it would have configured the default one as well. Mine certainly was, though I also have Visual Studio installed, which may have been responsible for that configuration.

There is an `add source` command that could probably get you going.

```
dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
```

If you're wanting to look into it more, https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior may be relevant. Your nuget.config file could be missing or invalid.

**Comment by pkothare** [comment]
Adding the source and re-running the commands fixed the issue. It correctly added the following `PackageReference` elements to the `GraphTutorial.csproj`

```
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="5.0.0" />
    <PackageReference Include="Microsoft.Graph" Version="3.22.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.25.0" />
    <PackageReference Include="TimeZoneConverter" Version="3.5.0" />
  </ItemGroup>
```
Thank you!
