### ISSUE TITLE
Getting the message ".NET Core Graph Tutorial needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it."

### ISSUE THREAD

**Issue by nadcraker** [microsoftgraph/msgraph-training-dotnet-core#3]
I followed the instructions exactly (or so I think of course), but when I attempt to visit `https://www.microsoft.com/devicelogin` I get the following error:

`.NET Core Graph Tutorial needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it.`

Under _Enterprise Applications > .NET Core Graph Tutorial - Permissions_ the following Admin consent is set:

![image](https://user-images.githubusercontent.com/5799503/70492612-d7cc8c00-1ab9-11ea-954e-712e644ae8e5.png)

**Comment by jasonjoh** [comment]
@nadcraker that permission "User.Read" isn't one that requires admin consent. However, it may be that your company has disabled your ability to consent to apps that your admins have not approved. If that's the case, that is the message you would see.
