### ISSUE TITLE
InvalidAuthenticationToken - CompactToken parsing failed with error code: 80049217

### ISSUE THREAD

**Issue by muqiuq** [microsoftgraph/msgraph-training-dotnet-core#31]
`GraphHelper.GetMeAsync()`
throws a Exception with at Line `Console.WriteLine($"Error getting signed-in user: {ex.Message}");`
It contains a Json with 
`{"error":{"code":"InvalidAuthenticationToken","message":"CompactToken parsing failed with error code: 80049217","innerError":{"date":"2021-07-23T10:07:16","request-id":"...","client-request-id":"..."}}}`

The devicelogin works flawless. What am I doing wrong?

**Comment by jasonjoh** [comment]
Can you login to [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer) with that same account and run the default query? The error indicates an issue with the access token, which may be tied to the user account you're using.
