### ISSUE TITLE
InteractiveBrowserCredential

### ISSUE THREAD

**Issue by DanielGoehler** [microsoftgraph/msgraph-training-dotnet-core#32]
How does other Credential Types like **InteractiveBrowserCredential** work with the example?

**Comment by jasonjoh** [comment]
I don't know! :D. This doesn't run in a browser so I'm not sure that it would work. If you try it let us know!

**Comment by DanielGoehler** [comment]
I don't how, that is why I asked. In this .NET Framework exampled a browser windows opens from this console app:
https://www.c-sharpcorner.com/article/write-your-first-program-using-microsoft-graph-sdk/

**Comment by jasonjoh** [comment]
I haven't done it either. Theoretically you could replace the DeviceCodeCredential with InteractiveBrowserCredential, but I don't know what sort of app registration requirements, etc. would be needed. Their [docs](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/identity/Azure.Identity/samples/ClientSideUserAuthentication.md#authenticating-users-with-the-interactivebrowsercredential) are a little light on details.

**Comment by DanielGoehler** [comment]
Thanks man, I try this out.

**Comment by jasonjoh** [comment]
I got around to trying this, and it is fairly simple. You need to add `http://localhost` as a redirect URI on your app registration.

```
var scopes = new[] { "User.Read" };

// Multi-tenant apps can use "common",
// single-tenant apps must use the tenant ID from the Azure portal
var tenantId = "common";

// Value from app registration
var clientId = "YOUR_CLIENT_ID";

var options = new InteractiveBrowserCredentialOptions
{
    TenantId = tenantId,
    ClientId = clientId,
    AuthorityHost = AzureAuthorityHosts.AzurePublicCloud,
    // MUST be http://localhost or http://localhost:PORT
    // See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/System-Browser-on-.Net-Core
    RedirectUri = new Uri("http://localhost"),
};

var interactiveCredential = new InteractiveBrowserCredential(options);

var graphClient = new GraphServiceClient(interactiveCredential, scopes);
```

**Comment by DanielGoehler** [comment]
I added http://localhost as Redirect URIs to the App Registration and the code to your GraphHelper and it works perfect. Thanks man!
```
    public class GraphHelper
    {
        //private static DeviceCodeCredential tokenCredential;
        private static InteractiveBrowserCredential tokenCredential;
        private static GraphServiceClient graphClient;

        public static void Initialize(string clientId, string[] scopes, Func<DeviceCodeInfo, CancellationToken, Task> callBack)
        {
            //tokenCredential = new DeviceCodeCredential(callBack, clientId); 
            tokenCredential = new InteractiveBrowserCredential(new InteractiveBrowserCredentialOptions
            {
                TenantId = "common",
                ClientId = clientId,
                AuthorityHost = AzureAuthorityHosts.AzurePublicCloud,
                RedirectUri = new Uri("http://localhost")
            });
            graphClient = new GraphServiceClient(tokenCredential, scopes);
        }
```
