### ISSUE TITLE
"You can't sign in here with a personal account. Use your work or school account instead."

### ISSUE THREAD

**Issue by simonsattin** [microsoftgraph/msgraph-training-dotnet-core#33]
I've followed the tutorial however when i run the app and then attempt to use the device login via browser using the code, i am unable to login with either my personal account (which is setup for Office 365) or a new outlook.com account i created to test this app. Perhaps something has changed in Azure that this tutorial has not taken into account?

![image](https://user-images.githubusercontent.com/11356932/127741821-870187f8-1b80-4197-8be0-13580330d7b9.png)

![image](https://user-images.githubusercontent.com/11356932/127741834-70c762da-9e7f-4ee9-8fcd-e88c4d94cdcb.png)

**Comment by jasonjoh** [comment]
I reproduce this as well. I know that Azure initially did not support personal accounts with device code flow, but they had enabled it. It may be that something's changed - stand by.

**Comment by jasonjoh** [comment]
Found the problem. This was from switching over to the new Azure.Identity library. It's an easy fix in code. In GraphHelper.cs, change this line in the `Initialize` function.

```
tokenCredential = new DeviceCodeCredential(callBack, clientId);
```

to this:

```
tokenCredential = new DeviceCodeCredential(callBack, "common", clientId);
```

**Comment by simonsattin** [comment]
Nice one that fixes it, thanks
