### ISSUE TITLE
Error in helper initialize

### ISSUE THREAD

**Issue by bilpor** [microsoftgraph/msgraph-training-dotnet-core#41]
HI,

I'm trying to follow your code example. I'm using VS2022 with .net core 6.0 and Blazor. I've created a standard class as opposed to a Blazor component for the code.

`tokenCredential = new DeviceCodeCredential(callBack, "common", clientId);
        _graphClient = new GraphServiceClient(tokenCredential, scopes);`

The 2 objects tokenCredential and scopes both red line in the the dev environment when trying to create the new GraphServiceClient.

Holding the mouse over tokenCredential gives:
Argument 1: Cannot convert from 'Azure.Identity.DeviceCodeCredential' to 'Microsoft.Graph.IAuthenticationProvider'

holding the mouse over scopes gives:
Argument2: Cannot convert from 'string[]' to 'Microsoft.Graph.IHttpProvider'

**Comment by jasonjoh** [comment]
Hi @bilpor! If you're building a Blazor app, `DeviceCodeCredential` isn't the way to go. Have you looked at our [Blazor tutorial](https://docs.microsoft.com/graph/tutorials/blazor)? [GitHub repo](https://github.com/microsoftgraph/msgraph-training-blazor-clientside)
